### ISSUE TITLE
Wrapping client instance into closure in tests

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/rust-libp2p-nym#19]
got it, anothor solution is wrapping them into a closure or you can just return the useless client and assign it to `_` xd

```rust
fn use_nym_client<R>(f: fn(dialer_uri: &str) -> R) -> R {
  ...
}

#[test]
fn test_with_nym_client() {
  use_nym_client(move |dialer_url| {
    let transport = NymTransport::new(dialer_uri, local_key).await?;
    ...
  }).expect("handle the result or throw errors")
}
```

_Originally posted by @clearloop in https://github.com/ChainSafe/rust-libp2p-nym/pull/12#discussion_r1154836611_

**Comment by noot** [comment]
i think this was closed with #24 ?
