### ISSUE TITLE
implement SURB flow for connections

### ISSUE THREAD

**Issue by noot** [ChainSafe/rust-libp2p-nym#3]
Nym uses SURBs (single use reply blocks) to allow a message recipient to anonymously reply to the sender. This can be used to implement bidirectional connections in the transport, such that the dialee does not know the Nym address of the dialer.

Flow:
- node A obtains the Nym address of node B and sends a message to node B along with X number of SURBs
- node B receives the message along with the SURBs. To respond, it uses 1 SURB to send a reply to node A. Node B remains unaware of node A’s Nym address.
- this can continue until node B is nearly out of SURBs, in which case they would need to request more SURBs from node A.

**Comment by empea-careercriminal** [comment]
In order to finish this project's timely, the optional SURBs flow has been marked out of scope.
